apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  generateName: ci-cd-pipeline-run-
spec:
  pipelineRef:
    name: ci-cd-pipeline
  workspaces:
    - name: source
      persistentVolumeClaim:
        claimName: oc-lab-pvc
  params:
    - name: repo-url
      value: "https://github.com/bilqeesajam/ci-cd-final-project.git"
    - name: branch
      value: "main"
    - name: app-name
      value: "counter-app"
    - name: build-image
      value: "image-registry.openshift-image-registry.svc:5000/sn-labs-ajambilqees/counter-app:latest"
